# ================================================ #
# Build and publish docker image with provided tag #
# ================================================ #

# Builds and published docker image tagged with provided tag.
name: dockerbuild
description: Build and push docker image
inputs:
  version:
    required: true
    description: A version to tag the docker image with
  gh_token:
    required: true
    description: Github token

runs:
  using: "composite"
  steps:

    - name: Setup Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6.1.0
      with:
        go-version: stable

    - name: Build
      shell: bash
      run: |
        CGO_ENABLED=0 \
        go build \
          -trimpath \
          -buildmode=pie \
          --ldflags="-s -w -X github.com/firebolt-db/otel-exporter/internal/collector.Version=${{ inputs.version }}" \
          -o ./otel-exporter .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130  # v3.7.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3.12.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.gh_token }}

    - name: Build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/firebolt-db/otel-exporter:${{ inputs.version }}
