services:
  firebolt-otel-exporter:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: firebolt-otel-exporter
    environment:
      - FIREBOLT_OTEL_EXPORTER_CLIENT_ID=
      - FIREBOLT_OTEL_EXPORTER_CLIENT_SECRET=
      - FIREBOLT_OTEL_EXPORTER_ACCOUNTS=eu-west-1
      - FIREBOLT_OTEL_EXPORTER_GRPC_ADDRESS=127.0.0.1:4317
      - FIREBOLT_OTEL_EXPORTER_LOG_LEVEL=debug
      - FIREBOLT_OTEL_EXPORTER_DATABASE=
    network_mode: host
  otel-collector:
    image: grafana/otel-lgtm
    ports:
      - 4317:4317 # OTLP http receiver
      - 4318:4318 # OTLP http receiver
      - 3000:3000 # grafana port